version: '3.5'
services:
  # product-service:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./src:/app/src
  #     - ./test:/app/test
  #   restart: on-failure
  #   environment:
  #     PORT: 3000
  #     LOG_LEVEL: debug

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=product
      - MYSQL_DATABASE=product-service
    volumes:
      - ${PWD}/local/mysql/data:/var/lib/mysql
      - ${PWD}/local/mysql/config/conf.d:/etc/mysql/conf.d

networks:
  default:
    name: 'product-service'
