version: '3.5'
services:
  # activity-service:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./src:/app/src
  #     - ./test:/app/test
  #   restart: on-failure
  #   environment:
  #     PORT: 3000
  #     LOG_LEVEL: debug
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: activity-service
    volumes:
      - ./local/mongodb/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  default:
    name: 'activity-service'
